"""Update RAG models with correct user_id type

Revision ID: af8f219c0c79
Revises: feec05bf95f5
Create Date: 2025-04-18 12:24:59.951402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af8f219c0c79'
down_revision = 'feec05bf95f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tools', 'configuration')
    op.drop_column('agent_tools', 'tool_type')
    op.drop_column('agent_tools', 'description')
    op.drop_column('process_tracking', 'process_type')
    op.drop_column('process_tracking', 'command')
    op.drop_column('workflows', 'initial_agent_id')
    op.drop_column('workflows', 'description')
    op.drop_column('workflows', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workflows', sa.Column('initial_agent_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('process_tracking', sa.Column('command', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('process_tracking', sa.Column('process_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('agent_tools', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agent_tools', sa.Column('tool_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('agent_tools', sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ### 