"""initial migration

Revision ID: 846885709f5f
Revises: 
Create Date: 2025-04-10 11:59:54.022394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846885709f5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 